// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.3
// 	protoc        v5.29.3
// source: proto/donor.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PrepareDonorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareDonorRequest) Reset() {
	*x = PrepareDonorRequest{}
	mi := &file_proto_donor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareDonorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareDonorRequest) ProtoMessage() {}

func (x *PrepareDonorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_donor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareDonorRequest.ProtoReflect.Descriptor instead.
func (*PrepareDonorRequest) Descriptor() ([]byte, []int) {
	return file_proto_donor_proto_rawDescGZIP(), []int{0}
}

func (x *PrepareDonorRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PrepareDonorRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type PrepareDonorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareDonorResponse) Reset() {
	*x = PrepareDonorResponse{}
	mi := &file_proto_donor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareDonorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareDonorResponse) ProtoMessage() {}

func (x *PrepareDonorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_donor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareDonorResponse.ProtoReflect.Descriptor instead.
func (*PrepareDonorResponse) Descriptor() ([]byte, []int) {
	return file_proto_donor_proto_rawDescGZIP(), []int{1}
}

func (x *PrepareDonorResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PrepareDonorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CommitDonorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitDonorRequest) Reset() {
	*x = CommitDonorRequest{}
	mi := &file_proto_donor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitDonorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitDonorRequest) ProtoMessage() {}

func (x *CommitDonorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_donor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitDonorRequest.ProtoReflect.Descriptor instead.
func (*CommitDonorRequest) Descriptor() ([]byte, []int) {
	return file_proto_donor_proto_rawDescGZIP(), []int{2}
}

func (x *CommitDonorRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CommitDonorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitDonorResponse) Reset() {
	*x = CommitDonorResponse{}
	mi := &file_proto_donor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitDonorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitDonorResponse) ProtoMessage() {}

func (x *CommitDonorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_donor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitDonorResponse.ProtoReflect.Descriptor instead.
func (*CommitDonorResponse) Descriptor() ([]byte, []int) {
	return file_proto_donor_proto_rawDescGZIP(), []int{3}
}

func (x *CommitDonorResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CommitDonorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RollbackDonorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackDonorRequest) Reset() {
	*x = RollbackDonorRequest{}
	mi := &file_proto_donor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackDonorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackDonorRequest) ProtoMessage() {}

func (x *RollbackDonorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_donor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackDonorRequest.ProtoReflect.Descriptor instead.
func (*RollbackDonorRequest) Descriptor() ([]byte, []int) {
	return file_proto_donor_proto_rawDescGZIP(), []int{4}
}

func (x *RollbackDonorRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type RollbackDonorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackDonorResponse) Reset() {
	*x = RollbackDonorResponse{}
	mi := &file_proto_donor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackDonorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackDonorResponse) ProtoMessage() {}

func (x *RollbackDonorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_donor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackDonorResponse.ProtoReflect.Descriptor instead.
func (*RollbackDonorResponse) Descriptor() ([]byte, []int) {
	return file_proto_donor_proto_rawDescGZIP(), []int{5}
}

func (x *RollbackDonorResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RollbackDonorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_donor_proto protoreflect.FileDescriptor

var file_proto_donor_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x6f, 0x6e, 0x6f, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x64, 0x6f, 0x6e, 0x6f, 0x72, 0x22, 0x42, 0x0a, 0x13, 0x50, 0x72,
	0x65, 0x70, 0x61, 0x72, 0x65, 0x44, 0x6f, 0x6e, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x4a,
	0x0a, 0x14, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x44, 0x6f, 0x6e, 0x6f, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x2d, 0x0a, 0x12, 0x43, 0x6f,
	0x6d, 0x6d, 0x69, 0x74, 0x44, 0x6f, 0x6e, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x49, 0x0a, 0x13, 0x43, 0x6f, 0x6d,
	0x6d, 0x69, 0x74, 0x44, 0x6f, 0x6e, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x22, 0x2f, 0x0a, 0x14, 0x52, 0x6f, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b,
	0x44, 0x6f, 0x6e, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x4b, 0x0a, 0x15, 0x52, 0x6f, 0x6c, 0x6c, 0x62, 0x61, 0x63,
	0x6b, 0x44, 0x6f, 0x6e, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x32, 0xe9, 0x01, 0x0a, 0x0c, 0x44, 0x6f, 0x6e, 0x6f, 0x72, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x47, 0x0a, 0x0c, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x44, 0x6f,
	0x6e, 0x6f, 0x72, 0x12, 0x1a, 0x2e, 0x64, 0x6f, 0x6e, 0x6f, 0x72, 0x2e, 0x50, 0x72, 0x65, 0x70,
	0x61, 0x72, 0x65, 0x44, 0x6f, 0x6e, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1b, 0x2e, 0x64, 0x6f, 0x6e, 0x6f, 0x72, 0x2e, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x44,
	0x6f, 0x6e, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x44, 0x0a, 0x0b,
	0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x44, 0x6f, 0x6e, 0x6f, 0x72, 0x12, 0x19, 0x2e, 0x64, 0x6f,
	0x6e, 0x6f, 0x72, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x44, 0x6f, 0x6e, 0x6f, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x64, 0x6f, 0x6e, 0x6f, 0x72, 0x2e, 0x43,
	0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x44, 0x6f, 0x6e, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x4a, 0x0a, 0x0d, 0x52, 0x6f, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x44, 0x6f,
	0x6e, 0x6f, 0x72, 0x12, 0x1b, 0x2e, 0x64, 0x6f, 0x6e, 0x6f, 0x72, 0x2e, 0x52, 0x6f, 0x6c, 0x6c,
	0x62, 0x61, 0x63, 0x6b, 0x44, 0x6f, 0x6e, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1c, 0x2e, 0x64, 0x6f, 0x6e, 0x6f, 0x72, 0x2e, 0x52, 0x6f, 0x6c, 0x6c, 0x62, 0x61, 0x63,
	0x6b, 0x44, 0x6f, 0x6e, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x08,
	0x5a, 0x06, 0x70, 0x62, 0x2f, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_donor_proto_rawDescOnce sync.Once
	file_proto_donor_proto_rawDescData = file_proto_donor_proto_rawDesc
)

func file_proto_donor_proto_rawDescGZIP() []byte {
	file_proto_donor_proto_rawDescOnce.Do(func() {
		file_proto_donor_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_donor_proto_rawDescData)
	})
	return file_proto_donor_proto_rawDescData
}

var file_proto_donor_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_donor_proto_goTypes = []any{
	(*PrepareDonorRequest)(nil),   // 0: donor.PrepareDonorRequest
	(*PrepareDonorResponse)(nil),  // 1: donor.PrepareDonorResponse
	(*CommitDonorRequest)(nil),    // 2: donor.CommitDonorRequest
	(*CommitDonorResponse)(nil),   // 3: donor.CommitDonorResponse
	(*RollbackDonorRequest)(nil),  // 4: donor.RollbackDonorRequest
	(*RollbackDonorResponse)(nil), // 5: donor.RollbackDonorResponse
}
var file_proto_donor_proto_depIdxs = []int32{
	0, // 0: donor.DonorService.PrepareDonor:input_type -> donor.PrepareDonorRequest
	2, // 1: donor.DonorService.CommitDonor:input_type -> donor.CommitDonorRequest
	4, // 2: donor.DonorService.RollbackDonor:input_type -> donor.RollbackDonorRequest
	1, // 3: donor.DonorService.PrepareDonor:output_type -> donor.PrepareDonorResponse
	3, // 4: donor.DonorService.CommitDonor:output_type -> donor.CommitDonorResponse
	5, // 5: donor.DonorService.RollbackDonor:output_type -> donor.RollbackDonorResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_donor_proto_init() }
func file_proto_donor_proto_init() {
	if File_proto_donor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_donor_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_donor_proto_goTypes,
		DependencyIndexes: file_proto_donor_proto_depIdxs,
		MessageInfos:      file_proto_donor_proto_msgTypes,
	}.Build()
	File_proto_donor_proto = out.File
	file_proto_donor_proto_rawDesc = nil
	file_proto_donor_proto_goTypes = nil
	file_proto_donor_proto_depIdxs = nil
}
