// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.1
// source: foundation.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FoundationService_GetOrderByID_FullMethodName             = "/foundation.FoundationService/GetOrderByID"
	FoundationService_PrepareAddOrderQuantity_FullMethodName  = "/foundation.FoundationService/PrepareAddOrderQuantity"
	FoundationService_CommitAddOrderQuantity_FullMethodName   = "/foundation.FoundationService/CommitAddOrderQuantity"
	FoundationService_RollbackAddOrderQuantity_FullMethodName = "/foundation.FoundationService/RollbackAddOrderQuantity"
)

// FoundationServiceClient is the client API for FoundationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FoundationServiceClient interface {
	GetOrderByID(ctx context.Context, in *OrderID, opts ...grpc.CallOption) (*GetOrderByIDResponse, error)
	PrepareAddOrderQuantity(ctx context.Context, in *PrepareAddOrderQuantityRequest, opts ...grpc.CallOption) (*PrepareAddOrderQuantityResponse, error)
	CommitAddOrderQuantity(ctx context.Context, in *CommitAddOrderQuantityRequest, opts ...grpc.CallOption) (*CommitAddOrderQuantityResponse, error)
	RollbackAddOrderQuantity(ctx context.Context, in *RollbackAddOrderQuantityRequest, opts ...grpc.CallOption) (*RollbackAddOrderQuantityResponse, error)
}

type foundationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFoundationServiceClient(cc grpc.ClientConnInterface) FoundationServiceClient {
	return &foundationServiceClient{cc}
}

func (c *foundationServiceClient) GetOrderByID(ctx context.Context, in *OrderID, opts ...grpc.CallOption) (*GetOrderByIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOrderByIDResponse)
	err := c.cc.Invoke(ctx, FoundationService_GetOrderByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *foundationServiceClient) PrepareAddOrderQuantity(ctx context.Context, in *PrepareAddOrderQuantityRequest, opts ...grpc.CallOption) (*PrepareAddOrderQuantityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrepareAddOrderQuantityResponse)
	err := c.cc.Invoke(ctx, FoundationService_PrepareAddOrderQuantity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *foundationServiceClient) CommitAddOrderQuantity(ctx context.Context, in *CommitAddOrderQuantityRequest, opts ...grpc.CallOption) (*CommitAddOrderQuantityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommitAddOrderQuantityResponse)
	err := c.cc.Invoke(ctx, FoundationService_CommitAddOrderQuantity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *foundationServiceClient) RollbackAddOrderQuantity(ctx context.Context, in *RollbackAddOrderQuantityRequest, opts ...grpc.CallOption) (*RollbackAddOrderQuantityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RollbackAddOrderQuantityResponse)
	err := c.cc.Invoke(ctx, FoundationService_RollbackAddOrderQuantity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FoundationServiceServer is the server API for FoundationService service.
// All implementations must embed UnimplementedFoundationServiceServer
// for forward compatibility.
type FoundationServiceServer interface {
	GetOrderByID(context.Context, *OrderID) (*GetOrderByIDResponse, error)
	PrepareAddOrderQuantity(context.Context, *PrepareAddOrderQuantityRequest) (*PrepareAddOrderQuantityResponse, error)
	CommitAddOrderQuantity(context.Context, *CommitAddOrderQuantityRequest) (*CommitAddOrderQuantityResponse, error)
	RollbackAddOrderQuantity(context.Context, *RollbackAddOrderQuantityRequest) (*RollbackAddOrderQuantityResponse, error)
	mustEmbedUnimplementedFoundationServiceServer()
}

// UnimplementedFoundationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFoundationServiceServer struct{}

func (UnimplementedFoundationServiceServer) GetOrderByID(context.Context, *OrderID) (*GetOrderByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrderByID not implemented")
}
func (UnimplementedFoundationServiceServer) PrepareAddOrderQuantity(context.Context, *PrepareAddOrderQuantityRequest) (*PrepareAddOrderQuantityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrepareAddOrderQuantity not implemented")
}
func (UnimplementedFoundationServiceServer) CommitAddOrderQuantity(context.Context, *CommitAddOrderQuantityRequest) (*CommitAddOrderQuantityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CommitAddOrderQuantity not implemented")
}
func (UnimplementedFoundationServiceServer) RollbackAddOrderQuantity(context.Context, *RollbackAddOrderQuantityRequest) (*RollbackAddOrderQuantityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RollbackAddOrderQuantity not implemented")
}
func (UnimplementedFoundationServiceServer) mustEmbedUnimplementedFoundationServiceServer() {}
func (UnimplementedFoundationServiceServer) testEmbeddedByValue()                           {}

// UnsafeFoundationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FoundationServiceServer will
// result in compilation errors.
type UnsafeFoundationServiceServer interface {
	mustEmbedUnimplementedFoundationServiceServer()
}

func RegisterFoundationServiceServer(s grpc.ServiceRegistrar, srv FoundationServiceServer) {
	// If the following call pancis, it indicates UnimplementedFoundationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FoundationService_ServiceDesc, srv)
}

func _FoundationService_GetOrderByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FoundationServiceServer).GetOrderByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FoundationService_GetOrderByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FoundationServiceServer).GetOrderByID(ctx, req.(*OrderID))
	}
	return interceptor(ctx, in, info, handler)
}

func _FoundationService_PrepareAddOrderQuantity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareAddOrderQuantityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FoundationServiceServer).PrepareAddOrderQuantity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FoundationService_PrepareAddOrderQuantity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FoundationServiceServer).PrepareAddOrderQuantity(ctx, req.(*PrepareAddOrderQuantityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FoundationService_CommitAddOrderQuantity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitAddOrderQuantityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FoundationServiceServer).CommitAddOrderQuantity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FoundationService_CommitAddOrderQuantity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FoundationServiceServer).CommitAddOrderQuantity(ctx, req.(*CommitAddOrderQuantityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FoundationService_RollbackAddOrderQuantity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RollbackAddOrderQuantityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FoundationServiceServer).RollbackAddOrderQuantity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FoundationService_RollbackAddOrderQuantity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FoundationServiceServer).RollbackAddOrderQuantity(ctx, req.(*RollbackAddOrderQuantityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FoundationService_ServiceDesc is the grpc.ServiceDesc for FoundationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FoundationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "foundation.FoundationService",
	HandlerType: (*FoundationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOrderByID",
			Handler:    _FoundationService_GetOrderByID_Handler,
		},
		{
			MethodName: "PrepareAddOrderQuantity",
			Handler:    _FoundationService_PrepareAddOrderQuantity_Handler,
		},
		{
			MethodName: "CommitAddOrderQuantity",
			Handler:    _FoundationService_CommitAddOrderQuantity_Handler,
		},
		{
			MethodName: "RollbackAddOrderQuantity",
			Handler:    _FoundationService_RollbackAddOrderQuantity_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "foundation.proto",
}
